export const images = {
  hamburger: require("./icon-hamburger.svg").default,
  illustration: require("./illustration.svg").default,
  lupa: require("./lupa.png").default,
  comida_1: require("./comida_1.svg").default,
  comida_2: require("./comida_2.svg").default,
  comida_3: require("./comida_3.svg").default,
  comida_4: require("./comida_4.svg").default,
  bloco_services: require("./bloco_services.svg").default,
  blog_image_1: require("./blog_image_1.svg").default,
  bloco_image_2: require("./bloco_image_2.svg").default,
  bloco_image_3: require("./bloco_image_3.svg").default,
  bloco_image_4: require("./bloco_image_4.svg").default,
  bloco_final_image: require("./bloco_final_image.svg").default,
  perfil: require("./icone.png").default,
};
